services:
    pg:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: test29
            POSTGRES_USER: test29
            POSTGRES_PASSWORD: test29
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U test29 -d test29"]
            interval: 5s
            timeout: 3s
            retries: 20

    php:
        build:
            context: .
            dockerfile: deploy/Dockerfile
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            pg:
                condition: service_healthy

    web:
        image: nginx:alpine
        ports:
            - "6080:80"
        volumes:
            - .:/var/www/html
            - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            php:
                condition: service_started

volumes:
    pgdata:
